site_name: AIMQ Documentation
site_description: Documentation for AIMQ - A robust message queue processor for Supabase pgmq with AI-powered document processing capabilities
repo_url: https://github.com/bldxio/aimq
repo_name: bldxio/aimq
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_bases: true
            merge_init_into_class: true
            docstring_section_style: table
            show_if_no_docstring: true
            preload_modules: [aimq]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md

  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Configuration: getting-started/configuration.md

  - User Guide:
      - Overview: user-guide/overview.md
      - Architecture: user-guide/architecture.md
      - CLI Commands: user-guide/cli.md
      - Supabase Setup: user-guide/supabase-setup.md
      - Defining Tasks:
          - Worker: user-guide/defining-tasks/worker.md
          - Helpers: user-guide/defining-tasks/helpers.md
          - Tools: user-guide/defining-tasks/tools.md
          - Langchain: user-guide/defining-tasks/langchain.md
      - Running Tasks:
          - Locally: user-guide/running-tasks/local.md
          - Docker: user-guide/running-tasks/docker.md
      - Examples:
          - Basic: user-guide/examples/basic.md

  - Tools:
      - tools/index.md
      - Supabase: tools/supabase.md
      - OCR: tools/ocr.md
      - PDF: tools/pdf.md
      - AI: tools/ai.md

  - Community:
      - Contributing: community/contributing.md
      - Testing: community/testing.md
      - Release Process: community/release-process.md
