name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}
    env:
      REGISTRY: registry.digitalocean.com/bldx
      REPOSITORY: aimq
      IMAGE_NAME: aimq
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker config.json for DOCR
        run: |
          mkdir -p ~/.docker
          echo '${{ secrets.DOCKER_CONFIG_JSON }}' > ~/.docker/config.json

      - name: Set image tag
        id: vars
        run: |
          # Use <git tag> if building from a tag, else <branch>-<shortsha>
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG="${GITHUB_REF##*/}"
          else
            BRANCH=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
            SHORT_SHA="${GITHUB_SHA::7}"
            TAG="${BRANCH}-${SHORT_SHA}"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Print image name
        run: echo "$REGISTRY/$REPOSITORY:$TAG"

      - name: Build and push Docker image
        run: |
          chmod +x ./docker/docker-build-push.sh
          ./docker/docker-build-push.sh "$REGISTRY" "$REPOSITORY" "$IMAGE_NAME" "$TAG"
